# Generated by Django 5.1.15 on 2026-08-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_simplemembershipplan_simpletrainer_gymmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='SimpleMembershipPlan',
        ),
        migrations.DeleteModel(
            name='SimpleTrainer',
        ),
        migrations.DeleteModel(
            name='GymMember',
        ),
    ]
